name: islam_mob_adhan
version: 0.0.1

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace

dev_dependencies:
  dart_numerics: ^0.0.6
  dependency_validator: 5.0.2
  enum_to_string: ^2.0.1
  intl: 0.20.2
  strings: ^3.1.2
  test: ^1.25.8
  path: ^1.9.1
  timezone: ^0.10.0
  islam_mob_lint: any
