name: islam_test
description: A package that provide utilities to make testing easier
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace
# Add regular dependencies here.
dependencies:
  flutter:
   sdk: flutter
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

dev_dependencies:
  dependency_validator: 5.0.2
  islam_mob_lint: any
