name: location_manager
version: 1.0.0
publish_to: 'none' 

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace
  
dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  logger_manager: any

dev_dependencies:
  build_runner: 2.7.1
  dependency_validator: 5.0.2
  flutter_test:
    sdk: flutter
  islam_mob_lint: any
  json_serializable: ^6.11.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
