name: azkar
version: 0.0.1

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace

dependencies:
  freezed: 3.2.3
  freezed_annotation: ^3.1.0

dev_dependencies:
  islam_mob_lint: any
  mockito: ^5.4.4
  dependency_validator: 5.0.2
