name: firebase_manager
version: 1.0.0
publish_to: none
environment:
  sdk: 3.8.1
  
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.6.12
  firebase_remote_config: ^5.5.0
  firebase_performance: ^0.10.1+10
  firebase_storage: ^12.4.10
  firebase_auth: ^5.7.0
  # firebase_core: ^3.6.0
  # firebase_analytics: ^11.3.3
  # firebase_crashlytics: ^4.3.5
  # firebase_messaging: ^15.1.3
  # cloud_firestore: ^5.4.4
  # firebase_remote_config: ^5.1.3
  # firebase_performance: ^0.10.0+8
  # firebase_storage: ^12.4.0
  # firebase_auth: ^5.6.0
  permission_handler: 12.0.0+1
  fpdart: ^1.1.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.0

  logger_manager:
    path: ../../utilities/logger_manager
  internet_connection_checkup:
    path: ../../utilities/internet_connection_checkup
    
dev_dependencies:
  islam_mob_lint:
    path: ../islam_mob_lint
  test: ^1.24.0
  dependency_validator: 4.1.0
