name: network_logging
description: Network request logging system for IslamMob
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dio: 5.8.0+1
  freezed_annotation: ^3.1.0
  injectable: 2.5.0
  get_it: 8.0.3
  uuid: ^4.5.1
  smooth_sheets: ^0.13.0

  logger_manager: any
  internet_connection_checkup: any

dev_dependencies:
  islam_mob_lint: any
  build_runner: 2.7.1
  freezed: 3.2.3
  json_serializable: ^6.11.1
  injectable_generator: 2.8.1
  dependency_validator: 5.0.2