name: advertisments_manager
version: 0.0.1

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0

dev_dependencies:
  islam_mob_lint: any
  dependency_validator: 5.0.2

flutter:
  uses-material-design: true