name: islam_mob_lint
description: "Lint rules and code style guidelines for Islam Mob projects"
publish_to: "none"
version: 1.0.0

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace

dependencies:
  analyzer: 7.6.0
  leancode_lint: 15.1.0
  logger_manager: any

dev_dependencies:
  dependency_validator: 5.0.2
