name: bdd_steps
description: BDD Steps
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

dev_dependencies:
  islam_mob_lint: any
  dependency_validator: 5.0.2
